### ISSUE TITLE
joining in room with alias doesn't work

### ISSUE THREAD

**Issue by silvio** [matrix-org/matrix-python-sdk#2]
I use the last tip of sdk with the patch in #1 .

code says more than thousend words (I got some warning regards to certification problem, I have hide this with `[...]`.

```
>>> from matrix_client.client import MatrixClient, Room
>>>
>>> username = "@silvio-test:localhost"
>>> password = "XXXXXX"
>>> hs = "https://localhost:8448"
>>>
>>> c = MatrixClient(hs, valid_cert_check=False)
>>>
>>> a = c.login_with_password(username, password)
[...]
>>> a
u'QHNpbHZpby10ZXN0OmxvY2FsaG9zdA...stbZxCrMkBDTEjwFPO'
>>> rs = c.get_rooms()
>>> rs
{u'!GCqRWAbXxwZvTiplaO:localhost': <matrix_client.client.Room object at 0x7f15aa8cf550>}
>>> r = rs['!GCqRWAbXxwZvTiplaO:localhost']
>>> r
<matrix_client.client.Room object at 0x7f15aa8cf550>
>>> r.aliases
[u'#testraum:localhost', u'#kuchenessenraum:localhost']
>>> ra = r.aliases[0]
>>> ra
u'#testraum:localhost'
>>> c.join_room(ra)
[...]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/matrix_client/client.py", line 91, in join_room
    response = self.api.join_room(room_id_or_alias)
  File "/usr/local/lib/python2.7/dist-packages/matrix_client/api.py", line 132, in join_room
    return self._send("POST", path)
  File "/usr/local/lib/python2.7/dist-packages/matrix_client/api.py", line 319, in _send
    code=response.status_code, content=response.text
matrix_client.api.MatrixRequestError: 500: {"error":"Internal server error"}
```

On server side I get in homeserver.log this messages:

```
2015-02-23 17:48:11,445 - synapse.http.server - 138 - INFO - POST-279 - Received request: POST /_matrix/client/api/v1/join/
2015-02-23 17:48:11,447 - synapse.http.server - 165 - ERROR - POST-279 - string index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/synapse/http/server.py", line 143, in _async_render
    *args
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/synapse/rest/client/v1/room.py", line 232, in on_POST
    identifier = RoomAlias.from_string(room_identifier)
  File "/usr/local/lib/python2.7/dist-packages/synapse/types.py", line 50, in from_string
    if s[0] != cls.SIGIL:
IndexError: string index out of range
2015-02-23 17:48:11,447 - twisted - 455 - INFO - POST-279 - "127.0.0.1" - - [23/Feb/2015:17:48:11 +0000] "POST /_matrix/client/api/v1/join/?access_token=QHNpbHZpby10ZXN0OmxvY2FsaG9zdA...stbZxCrMkBDTEjwFPO HTTP/1.1" 500 33 "-" "python-requests/2.5.1 CPython/2.7.3 Linux/3.18.2-2-ARCH"
2015-02-23 17:48:11,448 - synapse.http.server - 177 - INFO - POST-279 - Processed request: 2ms - POST /_matrix/client/api/v1/join/
```

If I join with the `room_id` seems to work:
```
>>> c.join_room('!GCqRWAbXxwZvTiplaO:localhost')
[...]
<matrix_client.client.Room object at 0x1201e10>
```
Logfile for this is here:

```
2015-02-23 17:59:01,038 - synapse.http.server - 138 - INFO - POST-304 - Received request: POST /_matrix/client/api/v1/join/!GCqRWAbXxwZvTiplaO:localhost
2015-02-23 17:59:01,040 - synapse.api.errors - 47 - INFO - POST-304 - SynapseError: 400, Expected RoomAlias string to start with '#'
2015-02-23 17:59:01,057 - twisted - 455 - INFO - GET-303 - "172.17.42.1" - - [23/Feb/2015:17:59:00 +0000] "GET /_matrix/client/api/v1/events?access_token=QHNpbHZpby10ZXN0OmxvY2FsaG9zdA...IBulaUdMGUgQjGKgNr&from=s12_22_10&timeout=30000 HTTP/1.1" 200 549 "https://localhost:8448/_matrix/client/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36"
2015-02-23 17:59:01,057 - synapse.http.server - 177 - INFO - GET-303 - Processed request: 2706ms 200 GET /_matrix/client/api/v1/events
2015-02-23 17:59:01,060 - twisted - 455 - INFO -  - "127.0.0.1" - - [23/Feb/2015:17:59:00 +0000] "POST /_matrix/client/api/v1/join/!GCqRWAbXxwZvTiplaO:localhost?access_token=QHNpbHZpby10ZXN0OmxvY2FsaG9zdA...stbZxCrMkBDTEjwFPO HTTP/1.1" 200 43 "-" "python-requests/2.5.1 CPython/2.7.3 Linux/3.18.2-2-ARCH"
2015-02-23 17:59:01,061 - synapse.http.server - 177 - INFO -  - Processed request: 22ms 200 POST /_matrix/client/api/v1/join/!GCqRWAbXxwZvTiplaO:localhost
2015-02-23 17:59:01,081 - synapse.http.server - 138 - INFO - GET-305 - Received request: GET /_matrix/client/api/v1/events
2015-02-23 17:59:01,085 - twisted - 455 - INFO - GET-305 - "172.17.42.1" - - [23/Feb/2015:17:59:00 +0000] "GET /_matrix/client/api/v1/events?access_token=QHNpbHZpby10ZXN0OmxvY2FsaG9zdA...IBulaUdMGUgQjGKgNr&from=s13_22_10&timeout=30000 HTTP/1.1" 200 229 "https://localhost:8448/_matrix/client/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36"
2015-02-23 17:59:01,085 - synapse.http.server - 177 - INFO - GET-305 - Processed request: 4ms 200 GET /_matrix/client/api/v1/events
2015-02-23 17:59:01,093 - synapse.http.server - 138 - INFO - GET-306 - Received request: GET /_matrix/client/api/v1/events
```

**Comment by silvio** [comment]
The same error occurs with the https://matrix.org/beta-hs.

**Comment by oddvar** [comment]
oops looks like we don't url-escape the room name! fixed in https://github.com/matrix-org/matrix-python-sdk/commit/0a97ec52

**Comment by silvio** [comment]
Yeaah! resolved. Thx @oddvar
