### ISSUE TITLE
Registering involves captcha

### ISSUE THREAD

**Issue by dryvenn** [matrix-org/matrix-python-sdk#82]
Hi,

First of all, thanks for the SDK, that helps a lot!

Now onto my issue: I followed `MatrixClient`'s example on registering an user and got back an error about captcha. Could this be a change in Matrix' protocol that wasn't propagated down here?

``` python
>>> from matrix_client.client import MatrixClient
>>> client = MatrixClient("https://matrix.org")
>>> token = client.register_with_password(username="foobar1234", password="password")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dryvenn/Downloads/matrix-python-sdk/matrix_client/client.py", line 126, in register_with_password
    "m.login.password", user=username, password=password
  File "/Users/dryvenn/Downloads/matrix-python-sdk/matrix_client/api.py", line 110, in register
    return self._send("POST", "/register", content)
  File "/Users/dryvenn/Downloads/matrix-python-sdk/matrix_client/api.py", line 459, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 400: {"errcode":"M_UNKNOWN","error":"Captcha is required."}
```

**Comment by Half-Shot** [comment]
Well, it's tricky...

Matrix.org (and some other servers that set this flag) requires a captcha for new registrants. There is no easy way for us to show the user a prompt for this in the SDK. However, we should be checking the server responses and at least letting the user know properly that they can't register with a captcha enabled server.

**Comment by GalPressman** [comment]
@Half-Shot Does that mean captcha registration will never be supported?
How does other other sdks handle this problem (for ex. js sdk)?

**Comment by GalPressman** [comment]
BTW, I can change the current behavior as you suggested if you wish.
What would you like to do if this situation arises? throw our own exception back to the user?

**Comment by Half-Shot** [comment]
To clear things up, registration is an API put in place for users to register accounts. If you are a bot wishing to make an account, you'd probably be after a AS service. So registration always assumes a human presence. 

It's hard to say exactly what to do right now because the [spec](http://matrix.org/docs/spec/client_server/r0.2.0.html) gives NO indication of what a captcha login response looks like (so if you could provide one for me, that would be useful). I presume it gives some sort of URL, which the user's client renders, which then gives a code which you use for the next stage of login. 

This SDK has primarily been used for bots and so user facing things such as this have never been considered. The JS/Android and IOS SDKs have all been designed for users first and thus things like this are usually tied to a UI of sorts so it's fairly easy to do this, since they are all tied to an existing UI.

The Python SDK needs to be able to have a callback which can then allow the application to either present the user with a UI to do so, and get the response back, or to deny the login request and throw an error if there is no way to provide the captcha. 

Sooo the TL;DR here is supporting it isn't a problem but there needs to be an easy way to present it.

**Comment by GalPressman** [comment]
Current response:
```
{
  "session": "tufbNNrohmOsAjTWDEyYeIZU",
  "params": {
    "m.login.recaptcha": {
      "public_key": "6Le31_kSAAAAAK-54VKccKamtr-MFA_3WS1d_fGV"
    }
  },
  "flows": [
    {
      "stages": [
        "m.login.recaptcha"
      ]
    },
    {
      "stages": [
        "m.login.email.identity",
        "m.login.recaptcha"
      ]
    }
  ]
}
```

Not sure how we can proceed from here though 😄 ,
I guess we should use the `public_key` somehow.

**Comment by kyrias** [comment]
You'd create a captcha widget with that key, and then submit the response back to matrix in the format specified in the spec.

**Comment by Half-Shot** [comment]
Simple as that, huh? Well then I'd just suggest the SDK needs to look into interactive login/registration processes rather than throwing the user&pass as the server and hoping it supports something like that, since it's very likely more authentication methods and multi-stage ones will become popular in the future. 

What I would suggest doing (and this is a much more involved process than simply writing a new function) is deprecating ``login_with_password`` and looking to have callbacks for the login/registration stages. It might be sensible to have something like ``begin_login([accepted_login_types], callback)`` which might call the callback for each stage.

It would be more complex, but it would allow us to support all sorts of exotic forms of login and registration effortlessly. 
Thoughts?

**Comment by GalPressman** [comment]
Seems reasonable, but don't we need to also provide a way for the user to query the different registration flows supported by the server before providing the callbacks?
Seems wrong to gather some callbacks from the user and try using them wishing for the best.

**Comment by Half-Shot** [comment]
You'd probably want to call ``/_matrix/client/r0/login`` as-is to get the login flows beforehand which would be another function. *However*, the same cannot be said for registration. It doesn't appear to give any indication of what flows are supported. 

To clarify on my idea, you'd call begin_login([flowset],callback) with the callback working something like:

begin_login(["password"], callback)

```python3
def callback(stage):
    if stage.type == "password":
         return {user,password}
    else if stage.type == "captcha":
         code = display_captcha(stage)
         return {code}
    throw HelpMe()
```

So I'd be more inclined to provide a single callback which deals with every type of stage.

**Comment by sbts** [comment]
@Half-Shot
Actually registration does return a list of flows.

 I'm poking at this looking for a solution to implement from a bash script.
Somewhat co-incidental.

**Comment by sbts** [comment]
{
    "completed": [
        "m.login.dummy"
    ],
    "flows": [
        {
            "stages": [
                "m.login.recaptcha"
            ]
        },
        {
            "stages": [
                "m.login.email.identity",
                "m.login.recaptcha"
            ]
        }
    ],
    "params": {
        "m.login.recaptcha": {
            "public_key": "6ae31_kSAAAAAK-34VKccKamtr-MFA_3WS1d_fGV"
        }
    },
    "session": "GxpVjXkdLKmUSHmBRFEXwllC"
}

**Comment by sbts** [comment]
The above was returned when running
```bash
        curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
            "bind_email": false,
            "password": "test",
            "username": "foo-test-1",
            "auth": {
                "type":"m.login.dummy"
            }
        }' "$state_baseURL/r0/register?kind=user"
```

**Comment by Half-Shot** [comment]
Oh I see, you gave it a kind first. Thanks

**Comment by vijaytabhatt** [comment]
Vijayta Bhatt, [05.10.20 23:14]
hello

i need one help , i have been trying to do registration process using recaptcha (i am using matrix public server which requires recaptcha

However whenever i send  my recaptcha response to server


it does not get accepted , which secret_key does server use to validate token?

i am following https://matrix.org/docs/spec/client_server/r0.3.0#post-matrix-client-r0-register
